###
#  This action actually executes Archy. Also, this is the first action where we created input values that we pass into the action.
#  You could re-use this action to deploy multiple flows.
name: "Publish Archy Flow"
description: "Use Archy to Publish Flows"
inputs:
  architect-flow-path: # id of input
    description: "The fully qualified directory and file name for the architect flow that will be published"
    required: true
  architect-results-path: # id of input
    description: "The fully qualified directory and file name for the results file executed by the flow. If you have multiple flows make sure you name each results file to be unique."
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd /home/runner/work/byTerraform/byTerraform/archy
        export PATH=$PATH:/archy
        ./archy publish --forceUnlock --file ./archy_flow.yml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location $GENESYSCLOUD_ARCHY_LOCATION --overwriteResultsFile --resultsFile ${{inputs.architect-results-path}}
        cat ${{inputs.architect-results-path}}
      shell: bash