name: "Invoke Terraform with Auto Apply"
description: "Invoke Terraform with Auto Apply"
runs:
  using: "composite"
  steps:
    - run: |
        terraform init 
        terraform apply --auto-approve
      shell: bash