
name: Architect Flow public API
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  
  Architect_flow:
    runs-on: ubuntu-latest
    env:
      GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}
      GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET }}
      GENESYSCLOUD_API_REGION: "https://api.mypure.cloud"
      GENESYSCLOUD_REGION: "us-east-1"
     
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/Install-Archy
      - uses: ./.github/genesys-cloud-apply-terraform
      - run: |
          pwd
      - uses: ./.github/publish-archy-flow
        with:
          architect-flow-path: $./archy
          architect-results-path: /home/runner/work/byTerraform/byTerraform/output/results.json
      
      